-- 過去の販売明細との参照を残すため、旧商品は削除せず販売停止にする。
UPDATE products
SET is_public = 0,
    is_active = 0,
    updated_at = datetime('now');

INSERT INTO products (
  id, name, display_name, category, price, initial_stock,
  is_public, is_active, sort_order,
  allergy_text, description, note,
  created_at, updated_at
) VALUES
('onigiri_shio', 'onigiri_shio', '塩', 'おにぎり', 200, 35, 1, 1, 1, '', '', '', datetime('now'), datetime('now')),
('onigiri_ume_official', 'onigiri_ume_official', '梅', 'おにぎり', 250, 30, 1, 1, 2, '', '', '', datetime('now'), datetime('now')),
('onigiri_shiso_kombu', 'onigiri_shiso_kombu', 'しそ昆布', 'おにぎり', 250, 20, 1, 1, 3, '', '', '', datetime('now'), datetime('now')),
('onigiri_okaka_official', 'onigiri_okaka_official', 'おかか', 'おにぎり', 250, 30, 1, 1, 4, '', '', '', datetime('now'), datetime('now')),
('onigiri_tuna_mayo_official', 'onigiri_tuna_mayo_official', 'ツナマヨ', 'おにぎり', 250, 50, 1, 1, 5, '', '', '', datetime('now'), datetime('now')),
('onigiri_takana_chirimen', 'onigiri_takana_chirimen', '高菜ちりめん', 'おにぎり', 250, 10, 1, 1, 6, '', '', '', datetime('now'), datetime('now')),
('onigiri_tori_soboro', 'onigiri_tori_soboro', 'とりそぼろ', 'おにぎり', 300, 15, 1, 1, 7, '', '', '', datetime('now'), datetime('now')),
('onigiri_teriyaki_chicken', 'onigiri_teriyaki_chicken', '照り焼きチキン', 'おにぎり', 250, 25, 1, 1, 8, '', '', '', datetime('now'), datetime('now')),
('onigiri_ebi_mayo', 'onigiri_ebi_mayo', 'エビマヨ', 'おにぎり', 300, 30, 1, 1, 9, '', '', '', datetime('now'), datetime('now')),
('onigiri_chanja', 'onigiri_chanja', 'チャンじゃ', 'おにぎり', 300, 30, 1, 1, 10, '', '', '', datetime('now'), datetime('now')),
('onigiri_yaki_tarako', 'onigiri_yaki_tarako', '焼きたらこ', 'おにぎり', 300, 40, 1, 1, 11, '', '', '', datetime('now'), datetime('now')),
('onigiri_kinira_nikumiso', 'onigiri_kinira_nikumiso', '黄ニラ肉みそ', 'おにぎり', 300, 35, 1, 1, 12, '', '', '', datetime('now'), datetime('now')),
('onigiri_karashi_mentaiko', 'onigiri_karashi_mentaiko', '辛子明太', 'おにぎり', 300, 50, 1, 1, 13, '', '', '', datetime('now'), datetime('now')),
('onigiri_sake_official', 'onigiri_sake_official', '鮭', 'おにぎり', 300, 30, 1, 1, 14, '', '', '', datetime('now'), datetime('now')),
('onigiri_ebi_tenmusu', 'onigiri_ebi_tenmusu', 'エビ天むす', 'おにぎり', 300, 25, 1, 1, 15, '', '', '', datetime('now'), datetime('now')),
('onigiri_nibuta_chashu', 'onigiri_nibuta_chashu', '煮豚チャーシュー', 'おにぎり', 350, 10, 1, 1, 16, '', '', '', datetime('now'), datetime('now')),
('side_karaage_official', 'side_karaage_official', '唐揚げ', 'サイドメニュー', 250, 200, 1, 1, 101, '', '', '', datetime('now'), datetime('now')),
('drink_ryokucha', 'drink_ryokucha', '緑茶', '飲み物', 100, 96, 1, 1, 201, '', '', '', datetime('now'), datetime('now')),
('drink_mugicha_official', 'drink_mugicha_official', '麦茶', '飲み物', 100, 96, 1, 1, 202, '', '', '', datetime('now'), datetime('now')),
('drink_calpis', 'drink_calpis', 'カルピス', '飲み物', 100, 72, 1, 1, 203, '', '', '', datetime('now'), datetime('now')),
('drink_ramune_official', 'drink_ramune_official', 'ラムネ', '飲み物', 100, 60, 1, 1, 204, '', '', '', datetime('now'), datetime('now')),
('drink_grape_juice', 'drink_grape_juice', 'グレープジュース', '飲み物', 100, 54, 1, 1, 205, '', '', '', datetime('now'), datetime('now')),
('drink_apple_juice', 'drink_apple_juice', 'りんごジュース', '飲み物', 100, 54, 1, 1, 206, '', '', '', datetime('now'), datetime('now')),
('drink_orange_juice', 'drink_orange_juice', 'オレンジジュース', '飲み物', 100, 54, 1, 1, 207, '', '', '', datetime('now'), datetime('now')),
('drink_aquarius', 'drink_aquarius', 'アクエリアス', '飲み物', 100, 72, 1, 1, 208, '', '', '', datetime('now'), datetime('now')),
('drink_cider', 'drink_cider', 'サイダー', '飲み物', 100, 72, 1, 1, 209, '', '', '', datetime('now'), datetime('now')),
('drink_water', 'drink_water', '水', '飲み物', 100, 72, 1, 1, 210, '', '', '', datetime('now'), datetime('now')),
('drink_nata_de_coco', 'drink_nata_de_coco', 'なたでここ', '飲み物', 100, 48, 1, 1, 211, '', '', '', datetime('now'), datetime('now'))
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  display_name = excluded.display_name,
  category = excluded.category,
  price = excluded.price,
  initial_stock = excluded.initial_stock,
  is_public = excluded.is_public,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  allergy_text = excluded.allergy_text,
  description = excluded.description,
  note = excluded.note,
  deleted_at = NULL,
  updated_at = excluded.updated_at;

INSERT INTO product_inventory (product_id, current_stock, updated_at) VALUES
('onigiri_shio', 35, datetime('now')),
('onigiri_ume_official', 30, datetime('now')),
('onigiri_shiso_kombu', 20, datetime('now')),
('onigiri_okaka_official', 30, datetime('now')),
('onigiri_tuna_mayo_official', 50, datetime('now')),
('onigiri_takana_chirimen', 10, datetime('now')),
('onigiri_tori_soboro', 15, datetime('now')),
('onigiri_teriyaki_chicken', 25, datetime('now')),
('onigiri_ebi_mayo', 30, datetime('now')),
('onigiri_chanja', 30, datetime('now')),
('onigiri_yaki_tarako', 40, datetime('now')),
('onigiri_kinira_nikumiso', 35, datetime('now')),
('onigiri_karashi_mentaiko', 50, datetime('now')),
('onigiri_sake_official', 30, datetime('now')),
('onigiri_ebi_tenmusu', 25, datetime('now')),
('onigiri_nibuta_chashu', 10, datetime('now')),
('side_karaage_official', 200, datetime('now')),
('drink_ryokucha', 96, datetime('now')),
('drink_mugicha_official', 96, datetime('now')),
('drink_calpis', 72, datetime('now')),
('drink_ramune_official', 60, datetime('now')),
('drink_grape_juice', 54, datetime('now')),
('drink_apple_juice', 54, datetime('now')),
('drink_orange_juice', 54, datetime('now')),
('drink_aquarius', 72, datetime('now')),
('drink_cider', 72, datetime('now')),
('drink_water', 72, datetime('now')),
('drink_nata_de_coco', 48, datetime('now'))
ON CONFLICT(product_id) DO NOTHING;
